%% BuildReportPDF.m — assemble all GrapherMatrix figures into one annotated PDF
%
% Produces GrapherMatrix_Report.pdf: a README/methods section (baseline +
% detector + smoother + regime + run-config explanations), then every figure
% from all 4 run configs, each on its own page with a descriptor blurb caption.
%
% Run:  matlab -batch "run('/home/troyboland/epr_imaging/epr_imaging/BuildReportPDF.m')"

baseDir = "/home/troyboland/epr_imaging/epr_imaging";
figRoot = fullfile(baseDir, "grapher_matrix_figs");
outPdf  = fullfile(baseDir, "GrapherMatrix_Report.pdf");
if exist(outPdf, "file"), delete(outPdf); end

runTags = ["masked", "nomask_log", "nomask_ceiling", "nomask_both"];
runDesc = struct( ...
    "masked",        "Speed/gap validity mask ON (original). 71% of the record retained. No spike suppression.", ...
    "nomask_log",    "No masking (100% retained). ALL channels log-scaled in both regimes so colossal multiplicative spikes compress and stop dragging the baseline up.", ...
    "nomask_ceiling","No masking (100% retained). Baseline-fit input clipped at each channel's 99th percentile; detection still sees true spike height. Most sensitive config.", ...
    "nomask_both",   "No masking (100% retained). Ceiling clip AND log-scaling combined.");

channels = ["CO2", "CH4", "O2", "temp"];   % altitude dropped (not a sensor channel)

% Combined cross-channel figures (one set per run, after the per-channel figures).
combBlurb = struct( ...
  "PAIR", ...
    "A channel PAIR overlaid on a shared robust-normalised (median/MAD) axis so different units compare directly (top), with each channel's anomaly-consensus track overlaid below - PURPLE where both channels flag together marks co-occurring anomalies. One figure per channel pair. Grey dashed = SAGE_WAND events.", ...
  "CONCURRENT_anomalies_cross_channel", ...
    "How many of the sensor channels are anomalous AT ONCE (top), with each channel's flag raster below. Peaks where all channels concur are the strongest multi-channel events - the ones to pull for the photogrammetry cross-check (question 3).", ...
  "CONCURRENT_anomalies_top_windows", ...
    "The top multi-channel concurrent-anomaly windows, ranked by how many channels concur and for how long. Each panel overlays all channels (robust-normalised) with the concurrent window shaded, and 2 min of context on each side, for direct inspection.");

% Figure-type descriptor blurbs (keyed by a token found in the filename).
figBlurb = struct( ...
  "baseline_comparison", ...
    "Four baseline MODELS overlaid on the channel (y-scaled to the baselines; plumes run off-scale). Red B1 running-median, blue B2 derivative-excision, green B3 robust low-pass, purple B4 polynomial. Lower panel: max-min disagreement between the four baselines - where the model choice matters. Grey = degraded (too-short) segments on a flat anchor. Grey dashed verticals = SAGE_WAND events.", ...
  "x16_strategies", ...
    "Top: the raw masked channel. Bottom: a 16-row raster (4 baselines x 4 detectors, S0none smoother slice, fine regime) showing which strategy flags which samples. Solid red = flagged. Reveals at a glance which combinations agree and which stand apart (typically the B4-polynomial rows).", ...
  "strategy_agreement_Jaccard", ...
    "16x16 heatmap of pairwise flagged-sample Jaccard overlap (1 = identical flags). The warm high-agreement block is the 12 moving-window strategies (B1/B2/B3 x any detector); the cold cross is the 4 B4-polynomial strategies - showing the baseline FAMILY matters more than the detector.", ...
  "consensus", ...
    "Top: the channel. Bottom: consensus track - how many of the 16 strategies flag each sample (0-16). Tall unanimous peaks are unambiguous events; broad moderate plateaus are sustained excursions that no single strategy fully resolves.", ...
  "smoothing_comparison", ...
    "Effect of input pre-smoothing, holding baseline+detector fixed (B4-poly + D1-hysteresis). Rows: None / Gaussian / moving-median / Savitzky-Golay / Hampel. Bottom bars: each smoother's flag agreement (Jaccard) with the no-smoothing control - ~1.0 means pre-smoothing changed nothing.", ...
  "anomaly_classification", ...
    "The payoff figure: BOTH regimes (fine + coarse, 160 strategies) merged and events classified by SCALE - LARGE (red, top-20% mass), LONG-SUSTAINED (orange, >=600 s), SHORT-TRANSIT (blue). Bottom: 0-160 consensus track. Grey dashed = SAGE_WAND events.");

%% ---- Build the document
% The Report Generator (rptgen) is not licensed here; use the base-MATLAB
% print/append path (exportgraphics with 'Append'), which needs no toolbox.
buildWithPrint(outPdf, figRoot, runTags, runDesc, channels, figBlurb, combBlurb, readmeText());
fprintf("Wrote %s\n", outPdf);


%% ======================================================================
function txt = readmeText()
%README/methods text, returned as a cell array of {heading, body} sections.
txt = {
"EPR Imaging - Baseline & Anomaly-Detection Method Report", ...
  ["This report compares a matrix of anomaly-detection strategies on the J1754 " ...
   "Jason dive sensor record (interp_full.csv, ~1 Hz, ~24 h) for the four SENSOR " ...
   "channels CO2 / CH4 / O2 / Temperature. Altitude is navigation, not a sensor, " ...
   "and is not analysed here. A known CO2 sensor-error window (05:07-05:44 on " ...
   "16 Jan, where the sensor sat at a flat floor value while the CO2/CH4 sensors " ...
   "were toggled) is blanked to NaN and excluded from every calculation. The " ...
   "report supports scientific-goal questions 1 (model the local drifting " ...
   "baseline) and 2 (identify anomalies as deviations). Comparison is visual and " ...
   "overlap-based - no ground truth, no scoring/ranking."]

"How the matrix is organised", ...
  ["Each strategy = one SMOOTHER x one BASELINE x one DETECTOR, run within two " ...
   "REGIMES (fine for short/subtle events, coarse for large/long), for a total of " ...
   "5 x 4 x 4 x 2 = 160 strategies per channel. Every channel is first oriented so " ...
   "an anomaly reads as a large POSITIVE residual: a per-channel sign flips " ...
   "depletion channels (O2), and a log flag is used where noise is multiplicative " ...
   "(CH4, fine regime only). The whole matrix is run once per RUN CONFIG (below)."]

"Baseline methods (question 1) - the per-timestamp model of the background", ...
  ["B1 MEDIAN FILTER: a wide running median (~4000 s) tracks slow drift by " ...
   "construction; iterative one-sided clipping removes the duty-cycle bias a plain " ...
   "median carries. Fails by the 50% law - an excursion over half the window pulls " ...
   "the baseline up into itself." newline ...
   "B2 DERIVATIVE EXCISION: finds event onsets from the robust-z of the derivative, " ...
   "walks each to its settle point, excises the whole event, and re-medians the " ...
   "hole-filled signal. Duration-agnostic (long plumes don't defeat it) but assumes " ...
   "sharp onsets." newline ...
   "B3 ROBUST GAUSSIAN LOW-PASS: an iterative one-sided outlier pre-pass strips " ...
   "whole plumes, then a Gaussian low-pass at a chosen cutoff period keeps only the " ...
   "slow background. Frequency-domain framing of the baseline." newline ...
   "B4 POLYNOMIAL DETREND: an iteratively-reweighted low-order polynomial fit to the " ...
   "quiet samples only - the ONLY closed-form model (coefficients you can write down " ...
   "and extrapolate). Structurally incapable of chasing a fast excursion, so it is " ...
   "the most robust to large plumes." newline ...
   "Degraded segments (too short to resolve drift) get a flat anchor at their own " ...
   "robust quiet level and are shaded grey."]

"Detector methods (question 2) - four different features of the residual", ...
  ["D1 HYSTERESIS (HEIGHT): enter above enterK sigma, hold until below exitK, reject " ...
   "sub-minimum-duration events. The reference detector." newline ...
   "D2 MASS (AREA): keeps candidate runs whose integrated positive residual " ...
   "(sigma-seconds) exceeds a self-referential robust fence - a low sustained plume " ...
   "and a tall brief spike judged on the same currency." newline ...
   "D3 PROMINENCE (SHAPE): findpeaks on the residual with a prominence threshold, " ...
   "then expand each peak to its shoulders - separates merged plumes, rejects slow " ...
   "shoulders." newline ...
   "D4 ISOUTLIER (LOCAL DISTRIBUTION): flags samples that are outliers vs their own " ...
   "local moving distribution, independent of the fitted sigma - an independent check " ...
   "on the noise model."]

"Smoothing axis + regimes", ...
  ["SMOOTHERS (applied to the baseline-fit input): S0none (control), S1 Gaussian, " ...
   "S2 moving-median, S3 Savitzky-Golay, S4 Hampel (edits only outliers). Detection " ...
   "still compares the ORIGINAL signal to the baseline, so smoothing changes the fit " ...
   "input, not the data judged." newline ...
   "REGIMES: fine (4000 s baseline window, tight limits - short transits) and coarse " ...
   "(20000 s window, relaxed limits, mass-first - large/long events a plume longer " ...
   "than half the fine window would otherwise be absorbed into the baseline). Both " ...
   "regimes' flags are merged and classified by scale."]

"Run configs (masking vs spike-suppression)", ...
  ["The speed-validity mask discards low-speed samples - but a vehicle hovering IN a " ...
   "plume is masked precisely when readings peak, and masking is a blunt way to keep " ...
   "colossal spikes from dragging a moving baseline up. So the matrix is run four " ...
   "ways: MASKED (original, 71% retained); NOMASK_LOG (no mask, log-scale all " ...
   "channels); NOMASK_CEILING (no mask, clip the baseline-fit input at the 99th " ...
   "percentile - detection still sees true height); NOMASK_BOTH (ceiling + log). " ...
   "Verified on CH4's 9395-peak spike: masking inflated the baseline to 878 (true " ...
   "background ~7) and missed it (0% flagged); all three suppression runs hold the " ...
   "baseline near 34 and catch it (71-75% flagged). No-masking recovers more events " ...
   "on every channel; nomask_ceiling is the most sensitive."]

"Figure types (per channel, per run)", ...
  ["BASELINE COMPARISON - the four baseline models overlaid + their disagreement. " ...
   "16 STRATEGIES - raster of which of the 16 fine strategies flag what. " ...
   "STRATEGY AGREEMENT (JACCARD) - 16x16 flag-overlap heatmap. " ...
   "CONSENSUS - how many strategies flag each sample. " ...
   "SMOOTHING COMPARISON - effect of pre-smoothing, fixed baseline+detector. " ...
   "ANOMALY CLASSIFICATION - both regimes merged, events coloured by scale class."]

"Combined cross-channel figures (end of each run)", ...
  ["PAIRWISE OVERLAYS - every channel pair overlaid on a shared robust-normalised " ...
   "axis, with the two anomaly-consensus tracks overlaid below; purple overlap = " ...
   "co-occurring anomalies. CROSS-CHANNEL CONCURRENT ANOMALIES - how many channels " ...
   "are anomalous at once, with per-channel flag rasters, so the strongest " ...
   "multi-channel events stand out. TOP CONCURRENT WINDOWS - the highest-concurrency " ...
   "windows zoomed with all channels overlaid, for direct inspection - the events " ...
   "to carry into questions 3-5 (photogrammetry / image-metric cross-checks)."]
};
txt = reshape(txt, 2, [])';   % Nx2 {heading, body}
end


%% ======================================================================
function buildWithReportGen(outPdf, baseDir, figRoot, runTags, runDesc, channels, figBlurb, readme) %#ok<INUSD>
import mlreportgen.dom.*;
d = Document(char(erase(outPdf, ".pdf")), "pdf");
open(d);

% Title + README/methods.
append(d, makeTitle("EPR Imaging - Anomaly-Detection Method Report"));
for i = 1:size(readme, 1)
    h = Heading2(char(readme{i, 1})); append(d, h);
    p = Paragraph(char(readme{i, 2})); p.Style = {FontSize("10pt")}; append(d, p);
end
append(d, PageBreak());

% Figures: run -> channel -> figure type.
typeOrder = ["baseline_comparison", "16_strategies", "strategy_agreement_Jaccard", ...
             "consensus", "smoothing_comparison", "anomaly_classification"];
for r = 1:numel(runTags)
    tag = runTags(r);
    h = Heading1(sprintf("Run: %s", tag)); append(d, h);
    pr = Paragraph(char(runDesc.(tag))); pr.Style = {FontSize("10pt"), Italic(true)}; append(d, pr);
    for c = 1:numel(channels)
        ch = channels(c);
        for tt = typeOrder
            f = findFig(figRoot, tag, ch, tt);
            if f == "", continue; end
            hh = Heading3(sprintf("%s - %s", ch, prettyType(tt))); append(d, hh);
            blurb = Paragraph(char(figBlurb.(matlab.lang.makeValidName(tt)))); blurb.Style = {FontSize("9pt")};
            append(d, blurb);
            img = Image(char(f)); img.Style = {ScaleToFit(true)}; append(d, img);
            append(d, PageBreak());
        end
    end
end
close(d);
end


%% ======================================================================
function buildWithPrint(outPdf, figRoot, runTags, runDesc, channels, figBlurb, combBlurb, readme)
% Fallback: no Report Generator. Render each page as a figure (text or image)
% and append to a multipage PDF with exportgraphics('Append').
    typeOrder = ["baseline_comparison", "16_strategies", "strategy_agreement_Jaccard", ...
                 "consensus", "smoothing_comparison", "anomaly_classification"];

    % --- README/methods text pages ---
    printTextPage(outPdf, "EPR Imaging - Anomaly-Detection Method Report", readme, true);
    % --- figures ---
    for r = 1:numel(runTags)
        tag = runTags(r);
        printSectionPage(outPdf, sprintf("RUN: %s", upper(tag)), runDesc.(tag));
        for c = 1:numel(channels)
            for tt = typeOrder
                f = findFig(figRoot, tag, channels(c), tt);
                if f == "", continue; end
                printImagePage(outPdf, ...
                    sprintf("%s  |  %s - %s", upper(tag), channels(c), prettyType(tt)), ...
                    figBlurb.(matlab.lang.makeValidName(tt)), f);
            end
        end
        % --- Combined cross-channel figures for this run ---
        combFiles = dir(fullfile(figRoot, char(tag), "PAIR_*.png"));
        combFiles = [combFiles;
                     dir(fullfile(figRoot, char(tag), "CONCURRENT_*.png"))];
        for cf = 1:numel(combFiles)
            fpath = string(fullfile(combFiles(cf).folder, combFiles(cf).name));
            nm = string(combFiles(cf).name);
            if startsWith(nm, "PAIR")
                blurb = combBlurb.PAIR;
                pageTitle = sprintf("%s  |  Combined - %s", upper(tag), erase(nm, ".png"));
            elseif contains(nm, "top_windows")
                blurb = combBlurb.CONCURRENT_anomalies_top_windows;
                pageTitle = sprintf("%s  |  Combined - Top concurrent-anomaly windows", upper(tag));
            else
                blurb = combBlurb.CONCURRENT_anomalies_cross_channel;
                pageTitle = sprintf("%s  |  Combined - Cross-channel concurrent anomalies", upper(tag));
            end
            printImagePage(outPdf, pageTitle, blurb, fpath);
        end
    end
end

function printTextPage(outPdf, titleStr, readme, isFirst)
%PRINTTEXTPAGE Flow the README onto pages using ONE multi-line text object per
% page (MATLAB handles line spacing), page-broken by a fixed line budget.  This
% avoids the per-line cursor overlap of manual positioning.  Headings are
% rendered with a leading ">>" and blank-line padding for visual separation.
    bodyW       = 105;    % wrap width (chars)
    linesPerPg  = 52;     % monospace lines that fit one portrait page at 8pt

    % Build one flat cellstr of lines (headings marked, bodies wrapped).  Every
    % readme cell is coerced to a scalar string first (they may arrive as char
    % row vectors or multi-piece strings, which would break scalar assignment).
    scalarStr = @(x) string(join(string(cellstr(x)), " "));
    all = strings(1,0);
    all(end+1) = ">>> " + scalarStr(titleStr);
    all(end+1) = "";
    for i = 1:size(readme,1)
        all(end+1) = ">> " + scalarStr(readme{i,1});            %#ok<AGROW> heading
        bl = splitlines(string(wrapText(readme{i,2}, bodyW)));
        all = [all, reshape(bl, 1, [])];                        %#ok<AGROW>
        all(end+1) = "";                                        %#ok<AGROW> spacer
    end

    % Emit in page-sized chunks, each as a single left-aligned monospace block.
    n = numel(all);
    for s = 1:linesPerPg:n
        e = min(s + linesPerPg - 1, n);
        block = strjoin(all(s:e), newline);
        fig = figure("Visible","off","Units","inches","Position",[0 0 8.5 11], ...
                 "Color","w","PaperUnits","inches","PaperSize",[8.5 11], ...
                 "PaperPosition",[0 0 8.5 11]);
        ax = axes(fig,"Position",[0.06 0.03 0.90 0.94]); axis(ax,"off"); %#ok<LAXES>
        ylim(ax,[0 1]); xlim(ax,[0 1]);
        text(ax, 0, 1, block, "FontName","FixedWidth", "FontSize", 8, ...
             "VerticalAlignment","top", "Interpreter","none");
        appendPage(fig, outPdf, isFirst); isFirst = false; close(fig);
    end
end

function printSectionPage(outPdf, titleStr, desc)
    fig = figure("Visible","off","Units","inches","Position",[0 0 8.5 11],"Color","w", ...
                 "PaperUnits","inches","PaperSize",[8.5 11],"PaperPosition",[0 0 8.5 11]);
    ax = axes(fig,"Position",[0.08 0 0.84 1]); axis(ax,"off"); ylim(ax,[0 1]); xlim(ax,[0 1]);
    text(ax,0,0.62,titleStr,"FontSize",22,"FontWeight","bold","Interpreter","none");
    text(ax,0,0.52,wrapText(desc,90),"FontSize",11,"VerticalAlignment","top","Interpreter","none");
    appendPage(fig, outPdf, false); close(fig);
end

function printImagePage(outPdf, titleStr, blurb, imgPath)
    % LANDSCAPE letter page (11 x 8.5) so the wide figures sit UPRIGHT at full
    % size - no head-tilting, maximum readability.  Title across the top, figure
    % filling the middle band at its native aspect, blurb along the bottom.
    fig = figure("Visible","off","Units","inches","Position",[0 0 11 8.5],"Color","w", ...
                 "PaperUnits","inches","PaperSize",[11 8.5],"PaperPosition",[0 0 11 8.5]);
    % Title (top)
    annotation(fig,"textbox",[0.03 0.955 0.94 0.04],"String",titleStr,"EdgeColor","none", ...
        "FontSize",13,"FontWeight","bold","Interpreter","none","VerticalAlignment","top");

    im = imread(char(imgPath));
    [ih, iw, ~] = size(im);

    % Image band between title and caption; fit preserving aspect, centred.
    bandY0 = 0.135;  bandY1 = 0.945;
    bandX0 = 0.02;   bandX1 = 0.98;
    bandW = bandX1-bandX0; bandH = bandY1-bandY0;
    pageAR = 11/8.5;                     % page width/height (normalized units use this)
    imgAR  = iw/ih;
    fitW = bandW; fitH = fitW * (1/imgAR) * pageAR;
    if fitH > bandH, fitH = bandH; fitW = fitH * imgAR / pageAR; end
    axX = bandX0 + (bandW - fitW)/2;
    axY = bandY0 + (bandH - fitH)/2;
    ax = axes(fig,"Position",[axX axY fitW fitH]);
    imshow(im,"Parent",ax,"Border","tight");

    % Blurb (bottom, full width)
    annotation(fig,"textbox",[0.03 0.015 0.94 0.105], ...
        "String",wrapText(blurb,155),"EdgeColor",[0.7 0.7 0.7], ...
        "FontSize",9.5,"Interpreter","none","VerticalAlignment","top", ...
        "BackgroundColor",[0.97 0.97 0.97]);
    appendPage(fig, outPdf, false); close(fig);
end

function appendPage(fig, outPdf, isFirst)
    % Export at high resolution so the embedded raster figures stay crisp.
    if isFirst
        exportgraphics(fig, outPdf, "ContentType","image", "Resolution", 220);
    else
        exportgraphics(fig, outPdf, "ContentType","image", "Resolution", 220, "Append", true);
    end
end


%% ======================================================================
function f = findFig(figRoot, tag, ch, typeToken)
    d = dir(fullfile(figRoot, char(tag), char(ch) + "_*" + char(typeToken) + "*.png"));
    if isempty(d), f = ""; else, f = string(fullfile(d(1).folder, d(1).name)); end
end

function s = prettyType(tt)
    m = struct("baseline_comparison","Baseline comparison", ...
               "x16_strategies","16-strategy raster", ...
               "strategy_agreement_Jaccard","Strategy agreement (Jaccard)", ...
               "consensus","Consensus", ...
               "smoothing_comparison","Smoothing comparison", ...
               "anomaly_classification","Anomaly classification");
    key = matlab.lang.makeValidName(tt);
    if isfield(m, key), s = string(m.(key)); else, s = tt; end
end

function out = wrapText(str, width)
%WRAPTEXT Word-wrap to `width` chars, honouring explicit newlines in the input.
    % Coerce to a single scalar string first: readme bodies may arrive as a
    % char row vector or a multi-piece string, either of which breaks splitlines.
    if isstring(str) && ~isscalar(str)
        str = strjoin(str, " ");
    end
    str = string(join(string(cellstr(str)), newline));  % char matrix rows -> newline-joined
    paras = splitlines(str);   % keep paragraph breaks from newline chars
    allLines = strings(0);
    for pi = 1:numel(paras)
        words = split(strtrim(paras(pi)));
        if numel(words) == 1 && words(1) == ""
            allLines(end+1) = ""; %#ok<AGROW>
            continue;
        end
        line = "";
        for wi = 1:numel(words)
            wr = words(wi);
            if strlength(line) == 0
                line = wr;
            elseif strlength(line) + strlength(wr) + 1 > width
                allLines(end+1) = line; line = wr; %#ok<AGROW>
            else
                line = line + " " + wr;
            end
        end
        if strlength(line) > 0, allLines(end+1) = line; end %#ok<AGROW>
    end
    out = char(strjoin(allLines, newline));
end

function h = makeTitle(~), h = []; end
